server:
  port:8080

spring:
  datasource:
    url: jdbc:mysql://49.235.232.153:3306/db_device_manage?serverTimezone=Asia/Shanghai
    username: octopigeon
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true